### ISSUE TITLE
Using the restart button does not reset the game timer. 

### ISSUE THREAD

**Issue by AstralShadow** [TheSunCat/Sudoku#15]
When playing on latest F-Droid release (1.1.2) i generated a new level using the interface under the board and my timer did not reset.

![Screenshot_20230201_081401_com.thesuncat.sudoku.jpg](https://user-images.githubusercontent.com/47869198/215966159-23ce29bd-89ac-4543-aa8e-46d32fa83054.jpg)

![Screenshot_20230201_081405_com.thesuncat.sudoku.jpg](https://user-images.githubusercontent.com/47869198/215966185-b448822e-b161-4ded-8fba-414c37892123.jpg)

**Comment by TheSunCat** [comment]
The intent is to provide players with a sense of pride and accomplishment for beating the puzzle on the first try... or it's just a bug lol. I'll fix it now. Thanks for the report!
