### ISSUE TITLE
Slower update for "remaining count" after upgrade to 1.2

### ISSUE THREAD

**Issue by sleep-yearning** [TheSunCat/Sudoku#17]
Thanks for making this app! I like it a lot. 
However, one smaller thing bugs me since the update to version 1.2:
When filling in a number, the field showing how many of that number are still missing updates with a delay now. 
This was not the case before and is a little annoying, since I got used to checking there if I'm done with this number.

Cheers

**Comment by TheSunCat** [comment]
I am happy to hear you like my app!
I can indeed reproduce this issue locally. Given this is a regression in 1.2, it is probably related to having split the game board into a separate widget, and not calling `setState` on the number buttons. Should be a quick fix but may have to wait until later this month (university finals...). Thank you for the report.
