### ISSUE TITLE
Leaderboard missing in Android 

### ISSUE THREAD

**Issue by urmomsangus** [TheSunCat/Sudoku#3]
Hi,  I download this game from F-Droid and played a game. I don't see an option that shows my previous scores.

Thanks, and great work on the game.

**Comment by urmomsangus** [comment]
Yeah, that would be awesome if the feature to see it outside of the game is available. Thanks again.

**Comment by TheSunCat** [comment]
You can now check your scores from the main menu:
![image](https://user-images.githubusercontent.com/44881120/195671093-c8029464-c17a-4550-877c-f3f4d373fc17.png)
