### ISSUE TITLE
A Small Request

### ISSUE THREAD

**Issue by Shadeclan** [TheSunCat/Sudoku#4]
The lines within the Sudoku squares are nearly invisible in dark mode. Could you lighten them up, maybe link them to the theme color? Thanks.

**Comment by TheSunCat** [comment]
Thanks for the feedback! That's a good idea. I will try out blending the background color and theme color, so they have less contrast than the main separators but more than they currently do.

**Comment by Shadeclan** [comment]
Thank you for your response!  I will look for the update.

**Comment by TheSunCat** [comment]
How does this look?
![image](https://user-images.githubusercontent.com/44881120/195660441-861ebd23-bd25-4b53-8e65-5cb132bd6586.png)

**Comment by Shadeclan** [comment]
The inbox lines seem better.  Can you do that in Orange?  :)

**Comment by TheSunCat** [comment]
![image](https://user-images.githubusercontent.com/44881120/195663891-85d00416-6c42-4128-8088-926503817df6.png)

**Comment by Shadeclan** [comment]
Sold!  I'll upgrade as soon as you have it ready for download on F-Droid!

Thanks!  I always prefer apps from people who are willing to listen.

**Comment by TheSunCat** [comment]
Always happy to hear and implement feedback! I also like this better :)
I'll make a new release soon fixing a couple bugs I've noticed myself, and then hopefully it will be on F-Droid within a day or two.

**Comment by Shadeclan** [comment]
Still looking ... :-)

**Comment by TheSunCat** [comment]
I, too, am still looking. This seems like a long time for F-Droid to wait before releasing the update... I will try to ask them.

**Comment by Shadeclan** [comment]
I thought that the developer controlled whether or not the app got updated.

**Comment by Shadeclan** [comment]
Excellent!  I actually checked again today to see if it was there.

**Comment by TheSunCat** [comment]
It's up on my end!

**Comment by Shadeclan** [comment]
... and it's downloaded on my end!  :-D

**Comment by Shadeclan** [comment]
Just brought it up.  Looks beautiful!  You did a great job, thanks!
