### ISSUE TITLE
[Bug] Validation fails when cells have markup

### ISSUE THREAD

**Issue by novellus** [TheSunCat/Sudoku#7]
A subset of cells with markup are incorrectly labeled as invalid when validation is run. See photo for example.
It looks like the intent was to only validate cells with a non-zero value.

Reproduction steps:
* Fill every cell with markup (any number[s])
* Run validation

Notes
* The incorrectly marked cells will re-mark as incorrect if validation is run again after markup is modified, markup removed and readded, or if a value is specified and then changed to markup.
* The incorrectly marked cells are not sensitive to the number contents of the markup, but do require at least one number in markup.
* The incorrectly marked cells are not invalidated if given a value rather than markup.
* The positions and number of incorrectly marked cells changes with each new game, so its possible that some games will have zero incorrectly marked cells.

![IMG_20221028_012353](https://user-images.githubusercontent.com/6426915/198741433-a576dc4f-8f40-4249-b10b-458f61709cf8.jpg)

**Comment by TheSunCat** [comment]
Thanks for the report! I indeed intended to only validate [cells that have an actual value input](https://github.com/TheSunCat/Sudoku/blob/main/lib/game.dart#L275) (not annotations), but clearly this is not working.
I could try to fix this by force-ignoring all cells that have markup, but unfortunately I can't seem to reproduce this issue. I've created five "Expert" games and filled every fillable cell with a markup, yet no cells are highlighted red when validating. Am I doing this wrong?

**Comment by novellus** [comment]
Interesting, I just tried as well and got the following results
* filled all cells with markup -> validate -> nothing wrong
* filled one cell with a number -> validate -> nothing wrong
* filled 2nd cell with a number  -> validate -> one marked up cell was invalidated
* filled 3rd cell with a number  -> validate -> two marked up cells were invalidated

**Comment by TheSunCat** [comment]
Thank you for the additional testing! This looks like the bugged board validation which I fixed with 18d0c3c73f07c59a6400dca9faa00fa56173a15c. I am running a build from source, hence I couldn't reproduce it! The fix should be out on F-Droid in a couple days at most (their build server has to pick up the new tagged release). I will keep this open until we can verify this doesn't happen on the latest F-Droid build.

**Comment by novellus** [comment]
This bug seems to be fixed in the latest build, marking as closed.
