### ISSUE TITLE
Highlighting Fails When Using UNDO

### ISSUE THREAD

**Issue by Shadeclan** [TheSunCat/Sudoku#8]
Hi, again.
If I delete pencil-marks then use the UNDO button to put them back, the numbers will not be highlighted.  This behavior persists even when switching back and forth between numbers.  

The work-around is to put the pencil-marks back in by hand.

**Comment by TheSunCat** [comment]
Thank you for the report! That is *so odd*, but yes I can reproduce it. I'll see if I have time later this week to fix it.

**Comment by Shadeclan** [comment]
Thanks.

**Comment by TheSunCat** [comment]
> I'll see if I have time later this week to fix it.
uhh where I come from weeks totally last two months

But hey, it's fixed now!

**Comment by Shadeclan** [comment]
Thank you!
